# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aic < Formula
  desc "Terminal AI CLI tool manager"
  homepage "https://github.com/xdx888999/aic"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xdx888999/aic/releases/download/v0.1.2/aic_darwin_amd64.tar.gz"
      sha256 "08c27c6bd2f4d24b181b4c24451c1755e4c7e6542381ad8d31c71a365328af57"

      define_method(:install) do
        bin.install "aic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xdx888999/aic/releases/download/v0.1.2/aic_darwin_arm64.tar.gz"
      sha256 "a0bf51105aa474e0701dbe60b9b192af6f0234c26fc159d6f95044dd3cdc7616"

      define_method(:install) do
        bin.install "aic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xdx888999/aic/releases/download/v0.1.2/aic_linux_amd64.tar.gz"
      sha256 "009235466e0a202d4a637e21ccb41300bf304b08a4d12542af258247dbb9b6fb"
      define_method(:install) do
        bin.install "aic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xdx888999/aic/releases/download/v0.1.2/aic_linux_arm64.tar.gz"
      sha256 "e855a2026c0f06b546f5bfe643497bfc66849a9164e29ffa6bb20c5ed8d3c301"
      define_method(:install) do
        bin.install "aic"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/aic --version")
  end
end
