# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aic < Formula
  desc "Terminal AI CLI tool manager"
  homepage "https://github.com/xdx888999/aic"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xdx888999/aic/releases/download/v0.1.5/aic_darwin_amd64.tar.gz"
      sha256 "d00daf527c495a029bd50023fbd4c7e964f5494d01a8394f2b90a412e4065ca0"

      def install
        bin.install "aic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xdx888999/aic/releases/download/v0.1.5/aic_darwin_arm64.tar.gz"
      sha256 "958e26ca938212a1301f8c2ef0814fe571e51b66b591568eee79bfbf7dad64b0"

      def install
        bin.install "aic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xdx888999/aic/releases/download/v0.1.5/aic_linux_amd64.tar.gz"
      sha256 "ddbea84dadca3499a01c362913c9134aa73028cf7b4baac9cf2bc248481ba355"
      def install
        bin.install "aic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xdx888999/aic/releases/download/v0.1.5/aic_linux_arm64.tar.gz"
      sha256 "d24d6ed50fde1478fc4b6d6b065da7fc614f0738869b63556e67757219cd8379"
      def install
        bin.install "aic"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/aic --version")
  end
end
