# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aic < Formula
  desc "Terminal AI CLI tool manager"
  homepage "https://github.com/xdx888999/aic"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xdx888999/aic/releases/download/v0.1.3/aic_darwin_amd64.tar.gz"
      sha256 "3d97da8b20f5759e22e6be36a47b07b198d148f765ccd893791fb7bd050a828d"

      define_method(:install) do
        bin.install "aic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xdx888999/aic/releases/download/v0.1.3/aic_darwin_arm64.tar.gz"
      sha256 "24eb11eb0a7e59e113ffa9c62f37020007b692ce3d3369fac3ea93e635c757f4"

      define_method(:install) do
        bin.install "aic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xdx888999/aic/releases/download/v0.1.3/aic_linux_amd64.tar.gz"
      sha256 "138926bf73520ddd1fcf7c3bd7d0a6f89c53ab712a8f9e996ae4b6e73120cd6e"
      define_method(:install) do
        bin.install "aic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xdx888999/aic/releases/download/v0.1.3/aic_linux_arm64.tar.gz"
      sha256 "9979ab73ee913a6ade5d9bcfb20dedce992988f8344c78feab887fdea0b816d1"
      define_method(:install) do
        bin.install "aic"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/aic --version")
  end
end
